<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


	<ItemGroup>
		<Content Remove="appsettings.Development.json" />
	</ItemGroup>


	<ItemGroup>
	  <None Include="appsettings.Development.json" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.22" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\..\..\protected\APIs\Shared\LylinkBackend_API_SharedMiddleware\LylinkBackend_API_Shared.csproj" />
	  <ProjectReference Include="..\..\..\protected\Clients\LylinkBackend.ManagementApiClient\LylinkBackend.ManagementApiClient.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\css\maintenance_style.css">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\js\categorizer.js">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\js\publisher.js">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


</Project>
