<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\private\Lylink.Shared.Models\Lylink.Shared.Models.csproj" />
    <ProjectReference Include="..\..\protected\Shared\Lylink.Shared.Api\Lylink.Shared.Api.csproj" />
  </ItemGroup>

</Project>
