<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\private\LylinkBackend.Repositories\LylinkBackend.Repositories.csproj" />
    <ProjectReference Include="..\..\Clients\LylinkBackend.SharedClientCode\LylinkBackend.SharedClientCode.csproj" />
    <ProjectReference Include="..\..\Management\LylinkBackend.ManagementShared\LylinkBackend.ManagementShared.csproj" />
    <ProjectReference Include="..\..\Shared\LylinkBackend.SharedApiCode\LylinkBackend.SharedApiCode.csproj" />
  </ItemGroup>

</Project>
